#!/usr/bin/env python

import timeit

def foo(iterable):
    return len(iterable)
lst = [i for i in range(10)]

print timeit.timeit('foo(lst)',
        setup='from __main__ import foo, lst')

# With python 3.5 and later, this is easier:
# print timeit.timeit('foo(lst)', globals=globals())

# example result:
# 0.0600519180298
