# -*- mode: ruby -*-
# vi: set ft=ruby :

# This is a terse Vagrantfile written for the intention of bringing up
# a machine with node.js and npm pre-installed, so they can jump
# directly into following the tic-tac-toe tutorial here:
#
# https://reactjs.org/tutorial/tutorial.html
#
# Target audience is recent graduates of Hackbright Academy, though
# anyone who finds it useful is welcome to use it; please consider it to
# be under the GPLv3 license, or ask me if you'd like other licensing
# (BSD, or whatever).



# For the rest of this vagrant configuration, I'll keep these comments
# less about what these configuration parameters /do/, and more about
# why I've used the settings I've chosen.  If you'd like to get a
# Vagrantfile with all the comments that normally come within one,
# which talk about what the options actually do, try typing the
# following in a shell:
#
#    vagrant init ubuntu/xenial64

Vagrant.configure("2") do |config|
  # as of the time of putting this here, I believe xenial to be the most
  # recent available ubuntu option:
  config.vm.box = "ubuntu/xenial64"

  # leaing this here and commented out just tot say: You needn't worry
  # too much if you start getting the error message from this.  That
  # said, you're welcome to either disable it by uncommenting this line
  # and changing false to true, or to do the vagrant box update that the
  # warning message will suggest.

  # config.vm.box_check_update = false

  # React (via 'npm start') uses port 3000 by default.  I'm setting it
  # to automatically set up using a different port if a port is in
  # use, in case
  config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true

  # put this directory under ~/src for the vagrant user, as a synced
  # folder (basically pretends to be the same exact filesystem).
  config.vm.synced_folder ".", "/home/vagrant/src"

  # config.vm.provider "virtualbox" do |vb|
  #   # I really doubt I need this:
  #   vb.gui = true
  #   # I'm less sure about this.  Leaving it with comments for the moment.
  #   vb.memory = "1024"
  # end

  # some provissioning to install node and npm, set up a shell prompt, and such:
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get -y upgrade
    apt-get install -y npm

    # make us able to do npm stuff as non-root:
    chgrp sudo /usr/local/*/
    chmod g+w /usr/local/*/
  SHELL

  # TODO: something to `npm start`?  Except I think I'm leaving this
  # where someone needs to create their own react app, so there's
  # nothing to start immediately.  Still, might be nice to have it
  # there for when they've built an app -- even if it's commented out
  # as an example.
end
